### ISSUE TITLE
Nodes in SignerList

### ISSUE THREAD

**Issue by jellicoe** [wojake/DKM#4]
how does contract find/determine the 10 nodes in the SignerList? and how do you check they are not running on the same Evernode hosts / hosts controlled by one actor

**Comment by wojake** [comment]
For context, DKM is not in charged of managing the network's UNL structure. The dApp is responsible to acquire HotPocket nodes from Evernode. In production, you would only want to acquire instances from reliable Evernode Hosts.

After acquiring instances from Evernode, you would want to include them to most of your dApp's nodes' UNL to make their validations effective in consensus.
